Controllers/DataController.cs
using DMPackageManager.Website.Database;
using DMPackageManager.Website.Models.Database;
using DMPackageManager.Website.Models.Page;
using DMPackageManager.Website.Util;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DMPackageManager.Website.Controllers {
    public class DataController : Controller {
        private readonly ILogger<DataController> _logger;
        private readonly DatabaseContext _dbc;

        public DataController(ILogger<DataController> logger, DatabaseContext dbc) {
            _logger = logger;
            _dbc = dbc;
        }

        /// <summary>
        /// Route to get the packages that belong to a user
        /// </summary>
        /// <param name="userName">The username to search for</param>
        /// <returns></returns>
        [Route("user/{username}")]
        [HttpGet]
        public IActionResult GetUserPackages(string userName = null, [FromQuery(Name = "p")] int page = 1) {
            // First check if they have a user
            bool userfound = _dbc.users.Where(x => x.username == userName).Any();
            if(userfound) {
                UserPackageList upl = new UserPackageList();
                upl.raw_username = userName;
                // Format their username
                upl.package_owner = UserUtil.FormatUser(userName, _dbc);
                upl.packages = FilterPackages(userName, null, page);
                upl.package_meta = FormatPackageMeta(upl.packages);
                if (UserUtil.IsLoggedIn(HttpContext) && (UserUtil.UserFromContext(HttpContext).username == upl.package_owner)) {
                    upl.own_packages = true;
                }
                return View("UserPackagesList", upl);
            } else {
                return NotFound(String.Format("The user '{0}' could not be found.", userName));
            }
            
        }

        /// <summary>
        /// Route to get all packages
        /// </summary>
        /// <param name="searchQuery">The username to search for</param>
        /// <returns></returns>
        [Route("packages")]
        [HttpGet]
        public IActionResult GetAllPackages([FromQuery(Name = "q")] string searchQuery = null, [FromQuery(Name = "p")] int page = 1) {
            SearchablePackageList spl = new SearchablePackageList();
            spl.packages = FilterPackages(null, searchQuery, page);
            spl.search_query = searchQuery;
            spl.package_meta = FormatPackageMeta(spl.packages);
            return View("PackagesList", spl);
        }

        /// <summary>
        /// Pulls up the results for a package
        /// </summary>
        /// <param name="packageTag">The tag of the package to search for</param>
        /// <param name="version">The (optional) version to load</param>
        /// <returns></returns>
        [Route("package/{packageTag}/{version?}")]
        public IActionResult GetPackage(string packageTag, string version) {
            if(String.IsNullOrWhiteSpace(packageTag)) {
                return BadRequest("No package name supplied");
            }
            // First we see if it exists
            if(!_dbc.packages.Where(p => p.package_name == packageTag).Any()) {
                return NotFound(String.Format("A package with ID `{0}` could not be found. Please check the name.", packageTag));
            }
            // If we have a version, check that version exists
            PackageInfo pi = new PackageInfo();
            pi.package = _dbc.packages.Where(p => p.package_name == packageTag).Include(p => p.owner).First();
            // Check if we own the package
            if(pi.package.owner.userId == UserUtil.UserFromContext(HttpContext).userId) {
                pi.owns_this_package = true;
            } else {
                pi.owns_this_package = false;
            }
            // Load all releases
            if (_dbc.package_releases.Where(r => r.package.id == pi.package.id).Any()) {
                pi.releases = _dbc.package_releases.Where(r => r.package.id == pi.package.id).OrderByDescending(r => r.release_date).ToList();
                // Setup counts
                PackageVersion PV = _dbc.package_releases.Where(r => r.package.id == pi.package.id).OrderByDescending(r => r.release_date).First();
                pi.package_meta.last_update = PV.release_date;
                pi.package_meta.latest_version = PV.version;
                pi.package_meta.total_downloads = _dbc.package_releases.Where(r => r.package.id == pi.package.id).Sum(r => r.download_count);
                // Are we targeting a specific version?
                if (!String.IsNullOrWhiteSpace(version)) {
                    if (!_dbc.package_releases.Where(p => p.package.id == pi.package.id).Where(p => p.version == version).Any()) {
                        return NotFound(String.Format("A package with ID `{0}` and version `{1}` could not be found. Please check the name.", packageTag, version));
                    }
                    pi.current_version = _dbc.package_releases.Where(p => p.package.id == pi.package.id).Where(p => p.version == version).First();
                } else {
                    // No? Lets just set our active to the first
                    pi.current_version = pi.releases.First();
                }
            }


            return View("PackageDetails", pi);
        }

        /// <summary>
        /// Helper to get packages and paginate them
        /// </summary>
        /// <param name="userName">The username to filter by, if any</param>
        /// <param name="searchQuery">The package name to filter by, if any</param>
        /// <param name="page">Which page to retrieve</param>
        /// <returns></returns>
        private PaginatedList<Package> FilterPackages(string userName = null, string searchQuery = null, int page = 1) {
            int pageSize = 50; // Tweak this as needed
            int offset = (pageSize * page) - pageSize;
            IQueryable<Package> query = _dbc.packages.Include(p => p.owner);
            if(!String.IsNullOrEmpty(userName)) {
                query = query.Where(p => p.owner.userId == UserUtil.Name2ID(userName, _dbc));
            }

            if(!String.IsNullOrEmpty(searchQuery)) {
                query = query.Where(p => p.package_name.Contains(searchQuery));
            }

            return PaginatedList<Package>.Create(query.OrderByDescending(p => p.creation_date).AsNoTracking(), page, pageSize);
        }

        private Dictionary<int, PackageDisplay> FormatPackageMeta(PaginatedList<Package> packages) {
            Dictionary<int, PackageDisplay> dict = new Dictionary<int, PackageDisplay>();
            foreach(Package P in packages) {
                // First grab the most recent version
                
                PackageDisplay PD = new PackageDisplay();
                // Presence check
                if (_dbc.package_releases.Where(r => r.package.id == P.id).Any()) {
                    PackageVersion PV = _dbc.package_releases.Where(r => r.package.id == P.id).OrderByDescending(r => r.release_date).First();
                    PD.latest_version = PV.version;
                    PD.last_update = PV.release_date;
                    // Now to get the download count
                    PD.total_downloads = _dbc.package_releases.Where(r => r.package.id == P.id).Sum(r => r.download_count);
                }
                dict[P.id] = PD;
            }
            return dict;
        }
    }
}

Controllers/MainController.cs
using DMPackageManager.Website.Database;
using DMPackageManager.Website.Models;
using DMPackageManager.Website.Models.Page;
using DMPackageManager.Website.Util;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DMPackageManager.Website.Controllers {
    [Route("")]
    public class MainController : Controller {
        private readonly ILogger<MainController> _logger;
        private readonly IConfiguration _configuration;
        private readonly DatabaseContext _dbc;

        public MainController(ILogger<MainController> logger, IConfiguration configuration, DatabaseContext dbc) {
            _logger = logger;
            _configuration = configuration;
            _dbc = dbc;
        }

        // Simple sign out
        [Route("logout")]
        public IActionResult Logout() {
            HttpContext.SignOutAsync();
            return Redirect("/");
        }

        [Route("")]
        public IActionResult Index() {
            return View();
        }

        [Route("packagespec")]
        public IActionResult PackageSpec() {
            return View("PackageSpec");
        }

        // High quality login handler
        [Authorize]
        [Route("login")]
        public IActionResult Login() {
            UserUtil.Save2DB(UserUtil.UserFromContext(HttpContext), _dbc);
            return Redirect("/");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [Route("error")]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_Layout.cshtml
@using DMPackageManager.Website.Util;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DMPM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">DMPM</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Main" asp-action="Index"><i class="fas fa-home"></i>&nbsp;Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="documentation_dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-file-alt"></i>&nbsp;Documentation
                            </a>
                            <div class="dropdown-menu" aria-labelledby="documentation_dropdown">
                                <a class="nav-link" asp-controller="Main" asp-action="Index"><i class="fas fa-download"></i>&nbsp;Installation</a>
                                <a class="nav-link" asp-controller="Main" asp-action="Index"><i class="fas fa-file-alt"></i>&nbsp;Client docs</a>
                                <a class="nav-link" asp-controller="Main" asp-action="PackageSpec"><i class="fas fa-cube"></i>&nbsp;Make a package</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Data" asp-action="GetAllPackages"><i class="fas fa-cubes"></i>&nbsp;Packages</a>
                        </li>
                        @if (UserUtil.IsLoggedIn(Context)) {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Data" asp-action="GetUserPackages" asp-route-userName="@UserUtil.UserFromContext(Context).username"><i class="fas fa-user"></i>&nbsp;My packages</a>
                            </li>
                        }
                    </ul>
                </div>
                @if (UserUtil.IsLoggedIn(Context)) {
                    <a class="nav-link btn btn-outline-primary btn-sm" asp-controller="Main" asp-action="logout"><i class="fas fa-sign-out-alt"></i>&nbsp;Logged in as @UserUtil.UserFromContext(Context).username - Logout</a>
                } else {
                    <a class="nav-link btn btn-outline-secondary btn-sm" asp-controller="Main" asp-action="login"><i class="fas fa-sign-in-alt"></i>&nbsp;Sign in (GitHub)</a>
                }

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer bg-light">
        <div class="container">
            &copy; DMPM Team - Not affiliated with BYOND - <a href="https://github.com/DMPM-Team/"><i class="fab fa-github"></i>&nbsp;Source / report issue</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>