Controllers/DataController.cs
using DMPackageManager.Website.Database;
using DMPackageManager.Website.Models.Database;
using DMPackageManager.Website.Models.Page;
using DMPackageManager.Website.Util;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DMPackageManager.Website.Controllers {
    public class DataController : Controller {
        private readonly ILogger<DataController> _logger;
        private readonly DatabaseContext _dbc;

        public DataController(ILogger<DataController> logger, DatabaseContext dbc) {
            _logger = logger;
            _dbc = dbc;
        }

        /// <summary>
        /// Route to get the packages that belong to a user
        /// </summary>
        /// <param name="userName">The username to search for</param>
        /// <returns></returns>
        [Route("user/{username}")]
        [HttpGet]
        public IActionResult GetUserPackages(string userName = null, [FromQuery(Name = "p")] int page = 1) {
            // First check if they have a user
            bool userfound = _dbc.users.Where(x => x.username == userName).Any();
            if(userfound) {
                UserPackageList upl = new UserPackageList();
                upl.raw_username = userName;
                // Format their username
                upl.package_owner = UserUtil.FormatUser(userName, _dbc);
                upl.packages = FilterPackages(userName, null, page);
                upl.package_meta = FormatPackageMeta(upl.packages);
                if (UserUtil.IsLoggedIn(HttpContext) && (UserUtil.UserFromContext(HttpContext).username == upl.package_owner)) {
                    upl.own_packages = true;
                }
                return View("UserPackagesList", upl);
            } else {
                return NotFound(String.Format("The user '{0}' could not be found.", userName));
            }
            
        }

        /// <summary>
        /// Route to get all packages
        /// </summary>
        /// <param name="searchQuery">The username to search for</param>
        /// <returns></returns>
        [Route("packages")]
        [HttpGet]
        public IActionResult GetAllPackages([FromQuery(Name = "q")] string searchQuery = null, [FromQuery(Name = "p")] int page = 1) {
            SearchablePackageList spl = new SearchablePackageList();
            spl.packages = FilterPackages(null, searchQuery, page);
            spl.search_query = searchQuery;
            spl.package_meta = FormatPackageMeta(spl.packages);
            return View("PackagesList", spl);
        }

        /// <summary>
        /// Pulls up the results for a package
        /// </summary>
        /// <param name="packageTag">The tag of the package to search for</param>
        /// <param name="version">The (optional) version to load</param>
        /// <returns></returns>
        [Route("package/{packageTag}/{version?}")]
        public IActionResult GetPackage(string packageTag, string version) {
            if(String.IsNullOrWhiteSpace(packageTag)) {
                return BadRequest("No package name supplied");
            }
            // First we see if it exists
            if(!_dbc.packages.Where(p => p.package_name == packageTag).Any()) {
                return NotFound(String.Format("A package with ID `{0}` could not be found. Please check the name.", packageTag));
            }
            // If we have a version, check that version exists
            PackageInfo pi = new PackageInfo();
            pi.package = _dbc.packages.Where(p => p.package_name == packageTag).Include(p => p.owner).First();
            // Check if we own the package
            if(pi.package.owner.userId == UserUtil.UserFromContext(HttpContext).userId) {
                pi.owns_this_package = true;
            } else {
                pi.owns_this_package = false;
            }
            // Load all releases
            if (_dbc.package_releases.Where(r => r.package.id == pi.package.id).Any()) {
                pi.releases = _dbc.package_releases.Where(r => r.package.id == pi.package.id).OrderByDescending(r => r.release_date).ToList();
                // Setup counts
                PackageVersion PV = _dbc.package_releases.Where(r => r.package.id == pi.package.id).OrderByDescending(r => r.release_date).First();
                pi.package_meta.last_update = PV.release_date;
                pi.package_meta.latest_version = PV.version;
                pi.package_meta.total_downloads = _dbc.package_releases.Where(r => r.package.id == pi.package.id).Sum(r => r.download_count);
                // Are we targeting a specific version?
                if (!String.IsNullOrWhiteSpace(version)) {
                    if (!_dbc.package_releases.Where(p => p.package.id == pi.package.id).Where(p => p.version == version).Any()) {
                        return NotFound(String.Format("A package with ID `{0}` and version `{1}` could not be found. Please check the name.", packageTag, version));
                    }
                    pi.current_version = _dbc.package_releases.Where(p => p.package.id == pi.package.id).Where(p => p.version == version).First();
                } else {
                    // No? Lets just set our active to the first
                    pi.current_version = pi.releases.First();
                }
            }


            return View("PackageDetails", pi);
        }

        /// <summary>
        /// Helper to get packages and paginate them
        /// </summary>
        /// <param name="userName">The username to filter by, if any</param>
        /// <param name="searchQuery">The package name to filter by, if any</param>
        /// <param name="page">Which page to retrieve</param>
        /// <returns></returns>
        private PaginatedList<Package> FilterPackages(string userName = null, string searchQuery = null, int page = 1) {
            int pageSize = 50; // Tweak this as needed
            int offset = (pageSize * page) - pageSize;
            IQueryable<Package> query = _dbc.packages.Include(p => p.owner);
            if(!String.IsNullOrEmpty(userName)) {
                query = query.Where(p => p.owner.userId == UserUtil.Name2ID(userName, _dbc));
            }

            if(!String.IsNullOrEmpty(searchQuery)) {
                query = query.Where(p => p.package_name.Contains(searchQuery));
            }

            return PaginatedList<Package>.Create(query.OrderByDescending(p => p.creation_date).AsNoTracking(), page, pageSize);
        }

        private Dictionary<int, PackageDisplay> FormatPackageMeta(PaginatedList<Package> packages) {
            Dictionary<int, PackageDisplay> dict = new Dictionary<int, PackageDisplay>();
            foreach(Package P in packages) {
                // First grab the most recent version
                
                PackageDisplay PD = new PackageDisplay();
                // Presence check
                if (_dbc.package_releases.Where(r => r.package.id == P.id).Any()) {
                    PackageVersion PV = _dbc.package_releases.Where(r => r.package.id == P.id).OrderByDescending(r => r.release_date).First();
                    PD.latest_version = PV.version;
                    PD.last_update = PV.release_date;
                    // Now to get the download count
                    PD.total_downloads = _dbc.package_releases.Where(r => r.package.id == P.id).Sum(r => r.download_count);
                }
                dict[P.id] = PD;
            }
            return dict;
        }
    }
}

Controllers/FileController.cs
using DMPackageManager.Website.Database;
using DMPackageManager.Website.Models.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace DMPackageManager.Website.Controllers {
    public class FileController : Controller {
        private readonly ILogger<FileController> _logger;
        private readonly DatabaseContext _dbc;

        public FileController(ILogger<FileController> logger, DatabaseContext dbc) {
            _logger = logger;
            _dbc = dbc;
        }

        [Route("download/{package_name}/{package_version}")]
        public IActionResult GetPackageZIP(string package_name, string package_version) {
            if (String.IsNullOrWhiteSpace(package_name)) {
                return BadRequest("Package name not supplied");
            }
            if (String.IsNullOrWhiteSpace(package_version)) {
                return BadRequest("Package version not supplied");
            }

            // Check for package
            if (!_dbc.packages.Where(p => p.package_name == package_name).Any()) {
                return NotFound(String.Format("The pacakge {0} could not be found.", package_name));
            }

            // Now check for releases
            Package P = _dbc.packages.Where(p => p.package_name == package_name).First();
            if(!_dbc.package_releases.Where(r => r.package == P).Where(r => r.version == package_version).Any()) {
                return NotFound(String.Format("Version {0} of pacakge {1} could not be found.", package_version, package_name));
            }

            PackageVersion PV = _dbc.package_releases.Where(r => r.package == P).Where(r => r.version == package_version).First();
            byte[] file_bytes = System.IO.File.ReadAllBytes(String.Format("App_Data/Package_Data/{0}/{1}.zip", P.id, PV.id));

            return File(file_bytes, "application/force-download", String.Format("{0}-{1}.zip", P.package_name, PV.version));
        }
    }
}

Views/Data/PackageDetails.cshtml
@{
    ViewData["Title"] = Model.package.package_name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model DMPackageManager.Website.Models.Page.PackageInfo; 
@using DMPackageManager.Website.Models.Database;

<div class="row">
    <div class="col col-8">
        <h1 class="display-4"><a asp-controller="Data" asp-action="GetUserPackages" asp-route-userName="@Model.package.owner.username">@Model.package.owner.username</a>/@Model.package.package_name</h1>
        @if (@Model.current_version != null) {
            <code>@Model.current_version.version</code>
            // Has to be div encased because thanks ASP
            <div>
                <hr />
                <code>dmpm.toml</code> entry:
                <div class="p-2 mb-2 bg-dark">
                    <code class="text-warning">"@Model.package.package_name" = "@Model.current_version.version"</code>
                </div>
            </div>
        }
        <p class="text-break">@Model.package.description</p>
        @if (Model.releases.Count > 0) {
            <hr />
            <h4>Release Notes</h4>
            <p id="releasenotesHolder">@Model.current_version.release_notes</p>
            <button class="btn btn-light btn-outline-dark btn-block mb-1" type="button" data-toggle="collapse" data-target="#releasesContainer" aria-expanded="false" aria-controls="releasesContainer">Show older releases</button>
            <div class="collapse" id="releasesContainer">
                <div class="card card-body">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th scope="col">Version</th>
                                <th scope="col">Downloads</th>
                                <th scope="col">Release Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (PackageVersion PV in Model.releases) {
                                <tr>
                                    <th scope="row"><a asp-controller="Data" asp-action="GetPackage" asp-route-packageTag="@Model.package.package_name" asp-route-version="@PV.version">@PV.version</a></th>
                                    <td>@PV.download_count</td>
                                    <td>@PV.release_date</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        }
    </div>
    <div class="col col-4">
        <h1 class="display-4">Info</h1>
        <hr />
        <ul class="list-unstyled">
            <li><i class="fas fa-calendar"></i>&nbsp;Created on @Model.package.creation_date</li>
            @if (!(Model.package_meta.last_update.CompareTo(DateTime.MinValue) == 0)) {
                // ASP makes me wrap this in spans. Pain
                <li><i class="fas fa-edit"></i>&nbsp;Updated on @Model.package_meta.last_update</li>
            }

            @if (!(Model.package_meta.latest_version == null)) {
                // ASP makes me wrap this in spans. Pain
                <li><i class="fas fa-tag"></i>&nbsp;Latest version: <a asp-controller="Data" asp-action="GetPackage" asp-route-packageTag="@Model.package.package_name" asp-route-version="@Model.package_meta.latest_version">@Model.package_meta.latest_version</a></li>
            }
            @if ((Model.current_version != null) && (!(Model.current_version.download_count == 0))) {
                // ASP makes me wrap this in spans. Pain
                <li><i class="fas fa-file-download"></i>&nbsp;@Model.current_version.download_count downloads (current version)</li>
            }
            @if (!(Model.package_meta.total_downloads == 0)) {
                // ASP makes me wrap this in spans. Pain
                <li><i class="fas fa-download"></i>&nbsp;@Model.package_meta.total_downloads downloads (all time)</li>
            }
        </ul>
        @if ((!(Model.package.source_url == null)) || (!(Model.package.documentation_url == null))) {
            <hr />
        }
    <ul class="list-unstyled">
        @if (!(Model.package.source_url == null)) {
            // ASP makes me wrap this in spans. Pain
            <li><i class="fab fa-git-alt"></i>&nbsp;<a href="@Model.package.source_url">Source Code</a></li>
        }
        @if (!(Model.package.documentation_url == null)) {
            // ASP makes me wrap this in spans. Pain
            <li><i class="fas fa-file-alt"></i>&nbsp;<a href="@Model.package.documentation_url">Documentation</a></li>
        }
        @if (!(Model.current_version == null)) {
            // ASP makes me wrap this in spans. Pain
    <li><i class="fas fa-file-archive"></i>&nbsp;<a asp-controller="File" asp-action="GetPackageZIP" asp-route-package_name="@Model.package.package_name" asp-route-package_version="@Model.current_version.version">Download zip</a></li>
        }
        
    </ul>
        @if (Model.owns_this_package) {
            <hr />
            <a class="btn btn-sm btn-primary" asp-controller="PackageManagement" asp-action="EditPackage" asp-route-package_name="@Model.package.package_name"><i class="fas fa-edit"></i>&nbsp;Edit Package</a>
            <a class="btn btn-sm btn-success" asp-controller="PackageManagement" asp-action="CreateNewRelease" asp-route-package_name="@Model.package.package_name"><i class="fas fa-plus"></i>&nbsp;New Release</a>
        }
    </div>
</div>
<script src="~/lib/markdown-it/markdown-it.min.js"></script>
<script>
    document.getElementById("releasenotesHolder").innerHTML = window.markdownit().render(document.getElementById("releasenotesHolder").innerHTML)
</script>

Views/Data/PackagesList.cshtml
@{
    ViewData["Title"] = "All packages";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model DMPackageManager.Website.Models.Page.SearchablePackageList;
@using DMPackageManager.Website.Models.Database;
@using DMPackageManager.Website.Util;
@{
    string prevDisabled = !Model.packages.HasPreviousPage ? "disabled" : "";
    string nextDisabled = !Model.packages.HasNextPage ? "disabled" : "";
    string searchExists = !String.IsNullOrEmpty(Model.search_query) ? Model.search_query : null;
}
<h1 class="display-4">All packages</h1>
<div class="mb-1">
    <form method="get" class="form-inline">
        <div class="form-actions no-color">
            <input class="form-control" type="text" name="q" value="@Model.search_query" placeholder="Search for a package..." />&nbsp;<input type="submit" value="Search" class="btn btn-primary" />
        </div>

        @if (Model.packages.HasPreviousPage) {
            <a asp-controller="Data" asp-action="GetAllPackages" asp-route-q="@searchExists" asp-route-p="@(Model.packages.PageIndex - 1)" class="ml-1 btn btn-primary @prevDisabled">Previous</a>
        }
        @if (Model.packages.HasNextPage) {
            <a asp-controller="Data" asp-action="GetAllPackages" asp-route-q="@searchExists" asp-route-p="@(Model.packages.PageIndex + 1)" class="ml-1 btn btn-primary @nextDisabled">Next</a>
        }
    </form>
</div>
@foreach (Package P in Model.packages) {
    <div class="card mt-3">
        <div class="card-body">
            <h4><a asp-controller="Data" asp-action="GetPackage" asp-route-packageTag="@P.package_name">@P.package_name</a> by <a asp-controller="Data" asp-action="GetUserPackages" asp-route-userName="@P.owner.username">@P.owner.username</a></h4>
            <p class="text-secondary">
                <i class="fas fa-calendar-alt"></i>&nbsp;Created on @P.creation_date
                @if (!(Model.package_meta[P.id].last_update.CompareTo(DateTime.MinValue) == 0)) {
                    // ASP makes me wrap this in spans. Pain
                    <span>&nbsp;<i class="fas fa-edit"></i>&nbsp;Updated on @Model.package_meta[P.id].last_update</span>
                }

                @if (!(Model.package_meta[P.id].latest_version == null)) {
                    // ASP makes me wrap this in spans. Pain
                    <span>&nbsp;<i class="fas fa-tag"></i>&nbsp;Latest version: @Model.package_meta[P.id].latest_version</span>
                }
                @if (!(Model.package_meta[P.id].total_downloads == 0)) {
                    // ASP makes me wrap this in spans. Pain
                    <span>&nbsp;<i class="fas fa-download"></i>&nbsp;@Model.package_meta[P.id].total_downloads downloads</span>
                }
            </p>
            <p class="text-wrap">@P.description</p>
        </div>
    </div>
}

Views/Data/UserPackagesList.cshtml
@{
    ViewData["Title"] = @Model.package_owner + "'s packages";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model DMPackageManager.Website.Models.Page.UserPackageList;
@using DMPackageManager.Website.Models.Database;
@using DMPackageManager.Website.Util;
@{
    string prevDisabled = !Model.packages.HasPreviousPage ? "disabled" : "";
    string nextDisabled = !Model.packages.HasNextPage ? "disabled" : "";
}
<h1 class="display-4">@Model.package_owner's packages</h1>
<div class="mb-1">
    @if (Model.own_packages) {
        // Check if we are looking at our own package list
        <a class="btn btn-success btn-sm" asp-controller="PackageManagement" asp-action="CreatePackage">Create Package</a>
    }
    @if (Model.packages.HasPreviousPage) {
        <a asp-controller="Data" asp-action="GetUserPackages" asp-route-userName="@Model.raw_username" asp-route-p="@(Model.packages.PageIndex - 1)" class="ml-1 btn btn-primary btn-sm @prevDisabled">Previous</a>
    }
    @if (Model.packages.HasNextPage) {
        <a asp-controller="Data" asp-action="GetUserPackages" asp-route-userName="@Model.raw_username" asp-route-p="@(Model.packages.PageIndex + 1)" class="ml-1 btn btn-primary btn-sm @nextDisabled">Next</a>
    }
</div>
@foreach (Package P in Model.packages) {
    <div class="card mt-3">
        <div class="card-body">
            <h4><a asp-controller="Data" asp-action="GetPackage" asp-route-packageTag="@P.package_name">@P.package_name</a> by <a asp-controller="Data" asp-action="GetUserPackages" asp-route-userName="@P.owner.username">@P.owner.username</a></h4>
            <p class="text-secondary">
                <i class="fas fa-calendar-alt"></i>&nbsp;Created on @P.creation_date
                @if (!(Model.package_meta[P.id].last_update.CompareTo(DateTime.MinValue) == 0)) {
                    // ASP makes me wrap this in spans. Pain
                    <span>&nbsp;<i class="fas fa-edit"></i>&nbsp;Updated on @Model.package_meta[P.id].last_update</span>
                }

                @if (!(Model.package_meta[P.id].latest_version == null)) {
                    // ASP makes me wrap this in spans. Pain
                    <span>&nbsp;<i class="fas fa-tag"></i>&nbsp;Latest version: @Model.package_meta[P.id].latest_version</span>
                }
                @if (!(Model.package_meta[P.id].total_downloads == 0)) {
                    // ASP makes me wrap this in spans. Pain
                    <span>&nbsp;<i class="fas fa-download"></i>&nbsp;@Model.package_meta[P.id].total_downloads downloads</span>
                }
            </p>
            <p class="text-wrap">@P.description</p>
        </div>
    </div>
}